### ISSUE TITLE
NodeUI header updates

### ISSUE THREAD

**Issue by ZygintasBudrys** [mysteriumnetwork/dvpn-web#507]
As NodeUI user I would like to see updated NodeUI header that would include:

- Node Status
- Node Quality
- NAT Status
- Next auto settlement

## Tasks to be done:

- [ ] Updated design for mobile and web view (current design to be supplemented by the missing info form the list above). Responsible person @skaiste
- [ ] Updated Tooltip text (that would be enough for user to understand the meaning of particular indicator and for more information a link included to help page/article). Responsible persons @Andzej + @Arturas and @Savannah to help with creating text attractive to users
- [ ] Dedicated help pages/articles created for each indicator (Node Status, Node Quality, NAT Status). The pages should explain what are possible values, what is their meaning and weather user should be taking any troubleshooting steps to improve. Responsible Person @Andzej + @Arturas and @Savannah to help with preparing text.
- [ ] Development (updating NodeUI with new designs, tooltip text, links)

## Agreed standards

1. Node Quality indicator
Good (Green) if quality value 0.75 - 3.0
Normal (Orange) if quality value <0.75 - 0.5
Poor (Red) if quality value <0.5
2. Node status "Monitoring failed" color indicator (Orange color not Red)
3. Node status "Pending" to be added after it is developed on infra level

##   Visuals
https://www.figma.com/file/aF3dmdLXWXIcabsGo6NpsT/MystNodes?type=design&node-id=158-718&mode=design&t=NnOE2dDnY48wTyU0-0

**Comment by ZygintasBudrys** [comment]
Additional requirements:
- When node is offline, the quality color indicator should turn grey.
